In [16]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report

In [17]:
data=pd.read_csv('a1_raw.csv')

In [18]:
data.head()

lhx       lhy       lhz       rhx       rhy       rhz        hx  \
0  5.347435  4.363681  1.501913  5.258967  4.319263  1.488703  5.037871   
1  4.869622  4.254210  1.556133  5.240113  4.346338  1.554309  5.037610   
2  5.357447  4.364039  1.500969  5.238928  4.347924  1.554150  5.037514   
3  4.942886  4.281878  1.546513  5.111436  4.229660  1.527091  5.037526   
4  5.003160  4.278530  1.542866  4.985812  4.182155  1.520330  5.037557   

         hy        hz        sx        sy        sz       lwx       lwy  \
0  1.618295  1.778350  5.062803  4.229656  1.772577  4.972902  4.301065   
1  1.618370  1.778573  5.061430  4.228504  1.772859  4.974908  4.303656   
2  1.618298  1.778774  5.059245  4.228004  1.773568  4.981612  4.305363   
3  1.618612  1.778855  5.056475  4.226891  1.774519  4.987158  4.304063   
4  1.619226  1.778925  5.052367  4.225485  1.775536  4.983912  4.296833   

        lwz       rwx       rwy       rwz  timestamp phase  
0  1.564781  5.553945  4.370456  1.553521    5702026  Rest  
1  1.565527  5.423875  4.303708  1.569942    5702058  Rest  
2  1.563643  5.332170  4.438061  1.572841    5702089  Rest  
3  1.565929  5.311104  4.396774  1.566368    5702120  Rest  
4  1.569889  5.193762  4.335417  1.560144    5702167  Rest

In [19]:
data.describe()

lhx          lhy          lhz          rhx          rhy  \
count  1747.000000  1747.000000  1747.000000  1747.000000  1747.000000   
mean      4.733099     4.110179     1.492067     5.400730     3.860213   
std       0.706462     0.782359     0.064146     0.807955     0.870350   
min       1.712471     1.660291     1.183290     3.653736     1.296046   
25%       4.530557     3.698007     1.467770     4.846750     3.274578   
50%       4.870256     4.266777     1.487985     5.199142     4.122335   
75%       5.153918     4.737138     1.524848     5.817285     4.374306   
max       6.212834     5.414431     1.673418     8.546903     5.453834   

               rhz           hx           hy           hz           sx  \
count  1747.000000  1747.000000  1747.000000  1747.000000  1747.000000   
mean      1.483939     5.084119     1.660346     1.753750     5.099306   
std       0.070478     0.181948     0.058347     0.024135     0.126167   
min       1.221158     4.435888     1.415457     1.664271     4.737700   
25%       1.458293     5.010395     1.632286     1.742879     5.041478   
50%       1.487003     5.073397     1.655894     1.757832     5.074966   
75%       1.517133     5.167158     1.678649     1.766782     5.141455   
max       1.722231     5.605544     1.965343     1.853095     5.586325   

                sy           sz          lwx          lwy          lwz  \
count  1747.000000  1747.000000  1747.000000  1747.000000  1747.000000   
mean      4.264994     1.742626     4.584839     4.110311     1.521522   
std       0.061245     0.016544     0.622707     0.683990     0.061683   
min       3.992892     1.698297     1.969708     1.953082     1.245345   
25%       4.235906     1.734144     4.417056     3.816689     1.502152   
50%       4.272721     1.740951     4.717515     4.236164     1.531247   
75%       4.297685     1.748727     4.936841     4.602459     1.554412   
max       4.822887     1.811931     5.798482     5.142542     1.668777   

               rwx          rwy          rwz     timestamp  
count  1747.000000  1747.000000  1747.000000  1.747000e+03  
mean      5.538275     3.902637     1.506997  5.739172e+06  
std       0.689032     0.786473     0.071968  2.796631e+04  
min       3.963918     1.643037     1.262197  5.702026e+06  
25%       5.084478     3.404305     1.478445  5.718500e+06  
50%       5.368165     4.146416     1.521121  5.734350e+06  
75%       5.845651     4.387562     1.544963  5.751136e+06  
max       8.266059     5.240774     1.719505  5.807537e+06

In [20]:
X=data.drop('phase',axis=1)
y=data['phase']

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.998 )

In [22]:
clf=SVC(kernel='sigmoid')
clf.fit(X_train, y_train)

ValueError: The number of classes has to be greater than one; got 1

In [13]:
y_pred=clf.predict(X_test)

In [14]:
cm=confusion_matrix(y_test, y_pred)

In [15]:
print(cm)

[[  0   0   0   0  39]
 [  0   0   0   0 162]
 [  0   0   0   0 698]
 [  0   0   0   0 191]
 [  0   0   0   0 654]]
